services:
  db-master:
    image: bitnami/postgresql:latest
    container_name: shipping_db_master
    restart: always
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_master_data:/bitnami/postgresql

  db-replica:
    image: bitnami/postgresql:latest
    container_name: shipping_db_replica
    restart: always
    depends_on:
      - db-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=db-master
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_replica_data:/bitnami/postgresql

  backend:
    build: ./backend
    container_name: shipping_api
    restart: always
    depends_on:
      - db-master
      - db-replica
    environment:
      - ConnectionStrings__DefaultConnection=Host=db-master,db-replica;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Target Session Attributes=prefer-primary;
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Google__ClientId=${GOOGLE_CLIENT_ID}
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - ./backend/wwwroot/uploads:/app/wwwroot/uploads

  frontend:
    build: ./frontend
    container_name: shipping_web
    restart: always
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"

volumes:
  postgres_master_data:
  postgres_replica_data:
