// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShippingAPI.Data;

#nullable disable

namespace ShippingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514082432_FixMissingAuditLogColumn")]
    partial class FixMissingAuditLogColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShippingAPI.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<int>("PerformedById")
                        .HasColumnType("integer");

                    b.Property<string>("PerformedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PerformedByRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecordId")
                        .HasColumnType("integer");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PerformedById");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ShippingAPI.Models.FuelClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinanceApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FinanceId")
                        .HasColumnType("integer");

                    b.Property<string>("FinanceNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ManagerApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("ManagerNote")
                        .HasColumnType("text");

                    b.Property<double>("MileageIn")
                        .HasColumnType("double precision");

                    b.Property<double>("MileageOut")
                        .HasColumnType("double precision");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("text");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FinanceId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("FuelClaims");
                });

            modelBuilder.Entity("ShippingAPI.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("DestinationLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("DestinationLng")
                        .HasColumnType("double precision");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<double?>("EndMileage")
                        .HasColumnType("double precision");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("OriginLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("OriginLng")
                        .HasColumnType("double precision");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("RouteDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("StartMileage")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TripNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TripNumber")
                        .IsUnique();

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("ShippingAPI.Models.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("ShippingAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$oB9.Nkzm0TeLV7/XJMrjJez171.HT0j4VALu/iQ2vW1h3SrLL95b6",
                            Role = 3,
                            Username = "admin",
                            VehiclePlate = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "",
                            FullName = "สมชาย ใจดี",
                            IsActive = true,
                            PasswordHash = "$2a$11$IUHhG9knJAspkVefizdBtOq7jpLlvAuAQLtnTc6iC2Ky4Zt9r2jvC",
                            Role = 0,
                            Username = "driver01",
                            VehiclePlate = ""
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "",
                            FullName = "นายวิชัย รักงาน",
                            IsActive = true,
                            PasswordHash = "$2a$11$yV0Zh3czIFTzcTlnBJqDLuRgvhVq.Az0L8Lq8bInekLmFI09eg11C",
                            Role = 1,
                            Username = "manager01",
                            VehiclePlate = ""
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "",
                            FullName = "นางสาวมาลี บัญชีดี",
                            IsActive = true,
                            PasswordHash = "$2a$11$6R2b8oXj5HEq2S4yiJ7qlu.FK3K.TZrbaDZ1a6Fb6BO.bBfT3YRSi",
                            Role = 2,
                            Username = "finance01",
                            VehiclePlate = ""
                        });
                });

            modelBuilder.Entity("ShippingAPI.Models.Withdrawal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalItems")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinanceApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FinanceId")
                        .HasColumnType("integer");

                    b.Property<string>("FinanceNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ManagerApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("ManagerNote")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FinanceId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("Withdrawals");
                });

            modelBuilder.Entity("ShippingAPI.Models.AuditLog", b =>
                {
                    b.HasOne("ShippingAPI.Models.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("ShippingAPI.Models.FuelClaim", b =>
                {
                    b.HasOne("ShippingAPI.Models.User", "Finance")
                        .WithMany()
                        .HasForeignKey("FinanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ShippingAPI.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ShippingAPI.Models.Shipment", "Shipment")
                        .WithMany("FuelClaims")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finance");

                    b.Navigation("Manager");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingAPI.Models.Shipment", b =>
                {
                    b.HasOne("ShippingAPI.Models.User", "Driver")
                        .WithMany("Shipments")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("ShippingAPI.Models.Withdrawal", b =>
                {
                    b.HasOne("ShippingAPI.Models.User", "Finance")
                        .WithMany()
                        .HasForeignKey("FinanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ShippingAPI.Models.User", "Manager")
                        .WithMany("ApprovedWithdrawals")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ShippingAPI.Models.Shipment", "Shipment")
                        .WithMany("Withdrawals")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finance");

                    b.Navigation("Manager");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingAPI.Models.Shipment", b =>
                {
                    b.Navigation("FuelClaims");

                    b.Navigation("Withdrawals");
                });

            modelBuilder.Entity("ShippingAPI.Models.User", b =>
                {
                    b.Navigation("ApprovedWithdrawals");

                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
